const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

const GET_USER_RESOURCES_REQUEST = "GET_USER_RESOURCES_REQUEST";
const GET_USER_RESOURCES_SUCCESS = "GET_USER_RESOURCES_SUCCESS";
const GET_USER_RESOURCES_FAILURE = "GET_USER_RESOURCES_FAILURE";

const GET_USER_BUILDINGS_REQUEST = "GET_USER_BUILDINGS_REQUEST";
const GET_USER_BUILDINGS_SUCCESS = "GET_USER_BUILDINGS_SUCCESS";
const GET_USER_BUILDINGS_FAILURE = "GET_USER_BUILDINGS_FAILURE";

const BUILDING_LEVEL_UP_REQUEST = "BUILDING_LEVEL_UP_REQUEST";
const BUILDING_LEVEL_UP_SUCCESS = "BUILDING_LEVEL_UP_SUCCESS";
const BUILDING_LEVEL_UP_FAILURE = "BUILDING_LEVEL_UP_FAILURE";

export default {
  LOGIN_USER_REQUEST,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAILURE,
  REGISTER_USER_REQUEST,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_FAILURE,
  GET_USER_RESOURCES_REQUEST,
  GET_USER_RESOURCES_SUCCESS,
  GET_USER_RESOURCES_FAILURE,
  GET_USER_BUILDINGS_REQUEST,
  GET_USER_BUILDINGS_SUCCESS,
  GET_USER_BUILDINGS_FAILURE,
  BUILDING_LEVEL_UP_REQUEST,
  BUILDING_LEVEL_UP_SUCCESS,
  BUILDING_LEVEL_UP_FAILURE
}