const GET_USER_RESOURCES_REQUEST = "GET_USER_RESOURCES_REQUEST";
const GET_USER_RESOURCES_SUCCESS = "GET_USER_RESOURCES_SUCCESS";
const GET_USER_RESOURCES_FAILURE = "GET_USER_RESOURCES_FAILURE";

const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export default {
  GET_USER_RESOURCES_REQUEST,
  GET_USER_RESOURCES_SUCCESS,
  GET_USER_RESOURCES_FAILURE,
  LOGIN_USER_REQUEST,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAILURE,
}