export default {
  LOGIN: 'Login',
  REGISTRATION: 'Registration',
  PASSWORD: 'Password',
  EMAIL: 'E-mail Address',
  USERNAME: 'Username',
  LOGIN_FAILURE_MESSAGE: 'Invalid email or password. Please try again!',
  REGISTER_FAILURE_MESSAGE: 'Something went wrong. Please try again!',
  NO_FLEET_MOVEMENT: "No fleet movement",
  WELCOME_TEXT: 'Welcome to OGame!',
  HOMEWORLD: 'Homeworld',
  BUILDINGS: 'Buildings',
  LOGO: 'Logo',
  COMMANDERS: 'Commanders',
  METAL_MINE: 'Metal mine',
  CRISTAL_MINE: 'Cristal mine',
  DEUTERIUM_MINE: 'Deuterium mine',
  LEVEL: 'Level',
  PRODUCTION_DURATION: 'Production duration',
  ENERGY_NEEDED: 'Energy needed',
  METAL_DESCRIPTION: 'Used in the extraction of metal ore, metal mines are of primary importance to all emerging and established empires.',
  CRISTAL_DESCRIPTION: 'Crystals are the main resource used to build electronic circuits and form certain alloy compounds.',
  DEUTERIUM_DESCRIPTION: 'Deuterium is used as fuel for spaceships and is harvested in the deep sea. Deuterium is a rare substance and is thus relatively expensive.',
  REQUIRED_TO_BUILD: 'Required to improve to level ',
  IMPROVE: 'Improve',
  OVERVIEW: 'Overview',
  RESEARCHES: 'Researches',
  ENERGY_TECHNOLOGY: 'Energy Technology',
  ENERGY_TECHNOLOGY_DESCRIPTION: 'The command of different types of energy is necessary for many new technologies.',
  RESEARCH_TIME: 'Research time',
};