export default {
  LOGIN: 'Login',
  REGISTRATION: 'Registration',
  PASSWORD: 'Password',
  EMAIL: 'E-mail Address',
  USERNAME: 'Username',
  LOGIN_FAILURE_MESSAGE: 'Invalid email or password. Please try again!',
  REGISTER_FAILURE_MESSAGE: 'Something went wrong. Please try again!',
  NO_FLEET_MOVEMENT: "No fleet movement",
  WELCOME_TEXT: 'Welcome to OGame!',
  HOMEWORLD: 'Homeworld',
  BUILDINGS: 'Buildings',
  LOGO: 'Logo',
  COMMANDERS: 'Commanders',
  METAL_MINE: 'Metal mine',
  LEVEL: 'Level',
  PRODUCTION_DURATION: 'Production duration',
  ENERGY_NEEDED: 'Energy needed',
  METAL_DESCRIPTION: 'Used in the extraction of metal ore, metal mines are of primary importance to all emerging and established empires.',
  REQUIRED_TO_BUILD: 'Required to improve to level ',
  IMPROVE: 'Improve',
  OVERVIEW: 'Overview',
  RESEARCH: 'Research',
};