export default {
  LOGIN: 'Login',
  REGISTRATION: 'Registration',
  PASSWORD: 'Password',
  EMAIL: 'E-mail Address',
  USERNAME: 'Username',
  LOGIN_FAILURE_MESSAGE: 'Invalid email or password. Please try again!',
  REGISTER_FAILURE_MESSAGE: 'Something went wrong. Please try again!',
  NO_FLEET_MOVEMENT: "No fleet movement",
  WELCOME_TEXT: 'Welcome to OGame!',
  HOMEWORLD: 'Homeworld',
  BUILDINGS: 'Buildings',
  LOGO: 'Logo',
  COMMANDERS: 'Commanders',
  METAL_MINE: 'Metal mine',
  CRISTAL_MINE: 'Cristal mine',
  DEUTERIUM_MINE: 'Deuterium mine',
  LEVEL: 'Level',
  PRODUCTION_DURATION: 'Production duration',
  ENERGY_NEEDED: 'Energy needed',
  METAL_DESCRIPTION: 'Used in the extraction of metal ore, metal mines are of primary importance to all emerging and established empires.',
  CRISTAL_DESCRIPTION: 'Crystals are the main resource used to build electronic circuits and form certain alloy compounds.',
  DEUTERIUM_DESCRIPTION: 'Deuterium is used as fuel for spaceships and is harvested in the deep sea. Deuterium is a rare substance and is thus relatively expensive.',
  REQUIRED_TO_BUILD: 'Required to improve to level ',
  IMPROVE: 'Improve',
  OVERVIEW: 'Overview',
  RESEARCHES: 'Researches',
  RESEARCH_TIME: 'Research time',
  ENERGY_TECHNOLOGY: 'Energy Technology',
  LASER_TECHNOLOGY: 'Laser Technology',
  ION_TECHNOLOGY: 'Ion Technology',
  HYPERSPACE_TECHNOLOGY: 'Hyperspace Technology',
  PLASMA_TECHNOLOGY: 'Plasma Technology',
  COMBUSTION_DRIVE: 'Combustion Drive',
  IMPULSE_DRIVE: 'Impulse Drive',
  HYPERSPACE_DRIVE: 'Hyperspace Drive',
  ESPIONAGE_TECHNOLOGY: 'Espionage Technology',
  COMPUTER_TECHNOLOGY: 'Computer Technology',
  ASTROPHYSICS: 'Astrophysics',
  INTERGALACTIC_RESEARCH_NETWORK: 'Intergalactic Research Network',
  GRAVITON_TECHNOLOGY: 'Graviton Technology',
  WEAPONS_TECHNOLOGY: 'Weapons Technology',
  SHIELDING_TECHNOLOGY: 'Shielding Technology',
  ARMOR_TECHNOLOGY: 'Armor Technology',
  ENERGY_TECHNOLOGY_DESCRIPTION: 'The command of different types of energy is necessary for many new technologies.',
  LASER_TECHNOLOGY_DESCRIPTION: 'Focusing light produces a beam that causes damage when it strikes an object.',
  ION_TECHNOLOGY_DESCRIPTION: 'The concentration of ions allows for the construction of cannons, which can inflict enormous damage and can reduce the deconstruction costs per level by 4%.',
  HYPERSPACE_TECHNOLOGY_DESCRIPTION: 'By integrating the 4th and 5th dimensions it is now possible to research a new kind of drive that is more economical and efficient. By using the fourth and fifth dimensions it is now possible to crumple the loading bays of your ships to save space.',
  PLASMA_TECHNOLOGY_DESCRIPTION: 'A further development of ion technology which accelerates high-energy plasma, which then inflicts devastating damage and additionally optimises the production of metal, crystal and deuterium (1%/0.66%/0.33% per level).',
  COMBUSTION_DRIVE_DESCRIPTION: 'The development of this drive makes some ships faster, although Each level only increases speed by 10 % of the base value.',
  IMPULSE_DRIVE_DESCRIPTION: 'The impulse drive is based on the reaction principle. Further development of this drive makes some ships faster, although each level only increases speed by 20 % of the base value.',
  HYPERSPACE_DRIVE_DESCRIPTION: 'Hyperspace drive warps space around a ship. The development of this drive makes some ships faster, although each level only increases speed by 30 % of the base value.',
  ESPIONAGE_TECHNOLOGY_DESCRIPTION: 'Information about other planets and moons can be gained using this technology.',
  COMPUTER_TECHNOLOGY_DESCRIPTION: 'More fleets can be commanded by increasing computer capacities. Each level of computer technology increases the maximum number of fleets by one.',
  ASTROPHYSICS_DESCRIPTION: 'With an astrophysics research module, ships can undertake long expeditions. Every second level of this technology will allow you to colonize an extra planet.',
  INTERGALACTIC_RESEARCH_NETWORK_DESCRIPTION: 'Researchers on different planets communicate via this network.',
  GRAVITON_TECHNOLOGY_DESCRIPTION: 'Firing a concentrated charge of graviton particles can create an artificial gravity field, which can destroy ships or even moons.',
  WEAPONS_TECHNOLOGY_DESCRIPTION: 'Weapons technology makes weapons systems more efficient. Each level of weapons technology increases the weapon strength of units by 10 % of the base value.',
  SHIELDING_TECHNOLOGY_DESCRIPTION: 'Shielding technology makes the shields on ships and defensive facilities more efficient. Each level of shield technology increases the strength of the shields by 10 % of the base value.',
  ARMOR_TECHNOLOGY_DESCRIPTION: 'Special alloys improve the armor on ships and defensive structures. The effectiveness of the armor can be increased by 10 % per level.',
};